//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            return null;
        }
    
    #endregion
    
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UtilizationTrackerDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.UtilizationTrackerData>
    {
    
        public UtilizationTrackerDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).UtilizationTrackerData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UtilizationTrackerDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.UtilizationTrackerData>
    {
        public UtilizationTrackerDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.AvgUtilization> AvgUtilization()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.AvgUtilization> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.AvgUtilization>("AvgUtilizations");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.CompanyProject> CompanySelfProjects()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.CompanyProject> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.CompanyProject>("CompanyProjects"),
                (c) => (c.EmpRole.CompareTo("Project Manager") == 0));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ComplexityandQualityShare> ProjectScore()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ComplexityandQualityShare> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ComplexityandQualityShare>("ComplexityandQualityShares");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DistinctProject> DistinctProjectList()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DistinctProject> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.DistinctProject>("DistinctProjects");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmailDropdown> EmailList()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmailDropdown> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmailDropdown>("EmailDropdowns");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeDetail> GetManagers()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeDetail> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeDetail>("EmployeeDetails"),
                (e) => (e.Role.CompareTo("Manager") == 0));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeDetail> UserName()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeDetail> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeDetail>("EmployeeDetails");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeDetail> ViewReportees()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeDetail> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeDetail>("EmployeeDetails");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeMonth> CandidateMonthDetails()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeMonth> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeMonth>("EmployeeMonths");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> Parameters(string MonthName, string ProjectName)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeProject>("EmployeeProjects"),
                    (e) => ((((MonthName == null) || (e.Months.MonthName.CompareTo(MonthName) == 0)) && ((ProjectName == null) || (e.ProjectDetail.ProjectName.CompareTo(ProjectName) == 0))) || (e.Months.MonthName.CompareTo("Null") == 0))),
                (e) => e.c_Date);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> Tracker()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeProject>("EmployeeProjects"),
                (e) => e.c_Date);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> ViewReporteeProjects()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeProject>("EmployeeProjects");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.HoursPerDay> NoOfHoursPerDay()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.HoursPerDay> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.HoursPerDay>("HoursPerDays");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.PMTeamProject> PMTeamProjectList()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.PMTeamProject> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.PMTeamProject>("PMTeamProjects");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ProjectDetail> CandidateProject()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ProjectDetail> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ProjectDetail>("ProjectDetails");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ProjectDetail> GetSelfProjects()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ProjectDetail> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ProjectDetail>("ProjectDetails");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ProjectReport> ProjectReportsforUser()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ProjectReport> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ProjectReport>("ProjectReports");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalHour> TotalWorkedHours()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalHour> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.TotalHour>("TotalHours");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject> TotalHoursForaProject()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject>("TotalHoursAllMonthsForProjects");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth> TotalHoursProjectWise()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.OrderBy(
                    this.GetQuery<global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth>("TotalHoursProjectwiseforMonths"),
                    (t) => t.ProjectName),
                (t) => t.MonthID);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalProjectScore> CandidateProjectScore()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.TotalProjectScore> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.TotalProjectScore>("TotalProjectScores");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.UtilizationCalculation> Utilization()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.UtilizationCalculation> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.UtilizationCalculation>("UtilizationCalculations");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.AssignProject))
            {
                return new global::LightSwitchApplication.Implementation.AssignProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.AvgUtilization))
            {
                return new global::LightSwitchApplication.Implementation.AvgUtilization();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.CompanyProject))
            {
                return new global::LightSwitchApplication.Implementation.CompanyProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.CompanyTeamProject))
            {
                return new global::LightSwitchApplication.Implementation.CompanyTeamProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ComplexityandQualityShare))
            {
                return new global::LightSwitchApplication.Implementation.ComplexityandQualityShare();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DistinctProject))
            {
                return new global::LightSwitchApplication.Implementation.DistinctProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmailDropdown))
            {
                return new global::LightSwitchApplication.Implementation.EmailDropdown();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeDetail))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeDetail();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeMonth))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeMonth();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeProjectHour))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeProjectHour();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeProject))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.GetDateParameter))
            {
                return new global::LightSwitchApplication.Implementation.GetDateParameter();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.HoursPerDay))
            {
                return new global::LightSwitchApplication.Implementation.HoursPerDay();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Months))
            {
                return new global::LightSwitchApplication.Implementation.Months();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.PMTeamProject))
            {
                return new global::LightSwitchApplication.Implementation.PMTeamProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectDetail))
            {
                return new global::LightSwitchApplication.Implementation.ProjectDetail();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectManagerViewTeamHour))
            {
                return new global::LightSwitchApplication.Implementation.ProjectManagerViewTeamHour();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectReport))
            {
                return new global::LightSwitchApplication.Implementation.ProjectReport();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectsInCompany))
            {
                return new global::LightSwitchApplication.Implementation.ProjectsInCompany();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectsInDay))
            {
                return new global::LightSwitchApplication.Implementation.ProjectsInDay();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TeamProject))
            {
                return new global::LightSwitchApplication.Implementation.TeamProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TeamProjectsList))
            {
                return new global::LightSwitchApplication.Implementation.TeamProjectsList();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalHour))
            {
                return new global::LightSwitchApplication.Implementation.TotalHour();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalHoursandProjectShare))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursandProjectShare();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalHoursofAllProject))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursofAllProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalHoursTeamMonthwise))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursTeamMonthwise();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TotalProjectScore))
            {
                return new global::LightSwitchApplication.Implementation.TotalProjectScore();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.UtilizationCalculation))
            {
                return new global::LightSwitchApplication.Implementation.UtilizationCalculation();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.UtilizationTracker))
            {
                return new global::LightSwitchApplication.Implementation.UtilizationTracker();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.UtilizationTrackerData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.UtilizationTrackerData(this.GetEntityConnectionString(
                "UtilizationTrackerData",
                "res://" + assemblyName + "/UtilizationTrackerData.csdl|res://" + assemblyName + "/UtilizationTrackerData.ssdl|res://" + assemblyName + "/UtilizationTrackerData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AssignProject))
            {
                return new global::LightSwitchApplication.Implementation.AssignProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AvgUtilization))
            {
                return new global::LightSwitchApplication.Implementation.AvgUtilization();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CompanyProject))
            {
                return new global::LightSwitchApplication.Implementation.CompanyProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CompanyTeamProject))
            {
                return new global::LightSwitchApplication.Implementation.CompanyTeamProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ComplexityandQualityShare))
            {
                return new global::LightSwitchApplication.Implementation.ComplexityandQualityShare();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DistinctProject))
            {
                return new global::LightSwitchApplication.Implementation.DistinctProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmailDropdown))
            {
                return new global::LightSwitchApplication.Implementation.EmailDropdown();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeDetail))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeMonth))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeMonth();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeProjectHour))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeProjectHour();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeProject))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.GetDateParameter))
            {
                return new global::LightSwitchApplication.Implementation.GetDateParameter();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.HoursPerDay))
            {
                return new global::LightSwitchApplication.Implementation.HoursPerDay();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Months))
            {
                return new global::LightSwitchApplication.Implementation.Months();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PMTeamProject))
            {
                return new global::LightSwitchApplication.Implementation.PMTeamProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectDetail))
            {
                return new global::LightSwitchApplication.Implementation.ProjectDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectManagerViewTeamHour))
            {
                return new global::LightSwitchApplication.Implementation.ProjectManagerViewTeamHour();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectReport))
            {
                return new global::LightSwitchApplication.Implementation.ProjectReport();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectsInCompany))
            {
                return new global::LightSwitchApplication.Implementation.ProjectsInCompany();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectsInDay))
            {
                return new global::LightSwitchApplication.Implementation.ProjectsInDay();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TeamProject))
            {
                return new global::LightSwitchApplication.Implementation.TeamProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TeamProjectsList))
            {
                return new global::LightSwitchApplication.Implementation.TeamProjectsList();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalHour))
            {
                return new global::LightSwitchApplication.Implementation.TotalHour();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalHoursAllMonthsForProject))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalHoursandProjectShare))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursandProjectShare();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalHoursofAllProject))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursofAllProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalHoursProjectwiseforMonth))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalHoursTeamMonthwise))
            {
                return new global::LightSwitchApplication.Implementation.TotalHoursTeamMonthwise();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TotalProjectScore))
            {
                return new global::LightSwitchApplication.Implementation.TotalProjectScore();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.UtilizationCalculation))
            {
                return new global::LightSwitchApplication.Implementation.UtilizationCalculation();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.UtilizationTracker))
            {
                return new global::LightSwitchApplication.Implementation.UtilizationTracker();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.UtilizationTrackerDataService))
            {
                return new global::LightSwitchApplication.UtilizationTrackerDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.UtilizationTrackerDataService))
            {
                return new global::LightSwitchApplication.Implementation.UtilizationTrackerDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AssignProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssignProject);
            }
            if (typeof(global::LightSwitchApplication.AvgUtilization) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AvgUtilization);
            }
            if (typeof(global::LightSwitchApplication.CompanyProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CompanyProject);
            }
            if (typeof(global::LightSwitchApplication.CompanyTeamProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CompanyTeamProject);
            }
            if (typeof(global::LightSwitchApplication.ComplexityandQualityShare) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ComplexityandQualityShare);
            }
            if (typeof(global::LightSwitchApplication.DistinctProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DistinctProject);
            }
            if (typeof(global::LightSwitchApplication.EmailDropdown) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmailDropdown);
            }
            if (typeof(global::LightSwitchApplication.EmployeeDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeDetail);
            }
            if (typeof(global::LightSwitchApplication.EmployeeMonth) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeMonth);
            }
            if (typeof(global::LightSwitchApplication.EmployeeProjectHour) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeProjectHour);
            }
            if (typeof(global::LightSwitchApplication.EmployeeProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeProject);
            }
            if (typeof(global::LightSwitchApplication.GetDateParameter) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.GetDateParameter);
            }
            if (typeof(global::LightSwitchApplication.HoursPerDay) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.HoursPerDay);
            }
            if (typeof(global::LightSwitchApplication.Months) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Months);
            }
            if (typeof(global::LightSwitchApplication.PMTeamProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PMTeamProject);
            }
            if (typeof(global::LightSwitchApplication.ProjectDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectDetail);
            }
            if (typeof(global::LightSwitchApplication.ProjectManagerViewTeamHour) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectManagerViewTeamHour);
            }
            if (typeof(global::LightSwitchApplication.ProjectReport) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectReport);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.ProjectsInCompany) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectsInCompany);
            }
            if (typeof(global::LightSwitchApplication.ProjectsInDay) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectsInDay);
            }
            if (typeof(global::LightSwitchApplication.TeamProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TeamProject);
            }
            if (typeof(global::LightSwitchApplication.TeamProjectsList) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TeamProjectsList);
            }
            if (typeof(global::LightSwitchApplication.TotalHour) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalHour);
            }
            if (typeof(global::LightSwitchApplication.TotalHoursAllMonthsForProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalHoursAllMonthsForProject);
            }
            if (typeof(global::LightSwitchApplication.TotalHoursandProjectShare) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalHoursandProjectShare);
            }
            if (typeof(global::LightSwitchApplication.TotalHoursofAllProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalHoursofAllProject);
            }
            if (typeof(global::LightSwitchApplication.TotalHoursProjectwiseforMonth) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalHoursProjectwiseforMonth);
            }
            if (typeof(global::LightSwitchApplication.TotalHoursTeamMonthwise) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalHoursTeamMonthwise);
            }
            if (typeof(global::LightSwitchApplication.TotalProjectScore) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TotalProjectScore);
            }
            if (typeof(global::LightSwitchApplication.UtilizationCalculation) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.UtilizationCalculation);
            }
            if (typeof(global::LightSwitchApplication.UtilizationTracker) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.UtilizationTracker);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssignProject :
        global::LightSwitchApplication.AssignProject.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssignProject.DetailsClass.IImplementation.EmployeeDetail
        {
            get
            {
                return this.EmployeeDetail;
            }
            set
            {
                this.EmployeeDetail = (global::LightSwitchApplication.Implementation.EmployeeDetail)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeDetail");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssignProject.DetailsClass.IImplementation.ProjectsInCompany
        {
            get
            {
                return this.ProjectsInCompany;
            }
            set
            {
                this.ProjectsInCompany = (global::LightSwitchApplication.Implementation.ProjectsInCompany)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ProjectsInCompany");
                }
            }
        }
        
        partial void OnEmpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeDetail");
            }
        }
        
        partial void OnProjectIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ProjectsInCompany");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AvgUtilization :
        global::LightSwitchApplication.AvgUtilization.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CompanyProject :
        global::LightSwitchApplication.CompanyProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CompanyTeamProject :
        global::LightSwitchApplication.CompanyTeamProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ComplexityandQualityShare :
        global::LightSwitchApplication.ComplexityandQualityShare.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DistinctProject :
        global::LightSwitchApplication.DistinctProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmailDropdown :
        global::LightSwitchApplication.EmailDropdown.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeDetail :
        global::LightSwitchApplication.EmployeeDetail.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeDetail.DetailsClass.IImplementation.EmployeeDetails
        {
            get
            {
                return this.EmployeeDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeDetail.DetailsClass.IImplementation.EmployeeDetail1
        {
            get
            {
                return this.EmployeeDetail1;
            }
            set
            {
                this.EmployeeDetail1 = (global::LightSwitchApplication.Implementation.EmployeeDetail)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeDetail1");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeDetail.DetailsClass.IImplementation.EmployeeMonths
        {
            get
            {
                return this.EmployeeMonths;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeDetail.DetailsClass.IImplementation.AssignProjects
        {
            get
            {
                return this.AssignProjects;
            }
        }
        
        partial void OnManagerIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeDetail1");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeMonth :
        global::LightSwitchApplication.EmployeeMonth.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeMonth.DetailsClass.IImplementation.EmployeeDetail
        {
            get
            {
                return this.EmployeeDetail;
            }
            set
            {
                this.EmployeeDetail = (global::LightSwitchApplication.Implementation.EmployeeDetail)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeDetail");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeMonth.DetailsClass.IImplementation.Months
        {
            get
            {
                return this.Months;
            }
            set
            {
                this.Months = (global::LightSwitchApplication.Implementation.Months)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Months");
                }
            }
        }
        
        partial void OnEmpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeDetail");
            }
        }
        
        partial void OnMonthIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Months");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeProjectHour :
        global::LightSwitchApplication.EmployeeProjectHour.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeProject :
        global::LightSwitchApplication.EmployeeProject.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeProject.DetailsClass.IImplementation.Months
        {
            get
            {
                return this.Months;
            }
            set
            {
                this.Months = (global::LightSwitchApplication.Implementation.Months)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Months");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeProject.DetailsClass.IImplementation.ProjectDetail
        {
            get
            {
                return this.ProjectDetail;
            }
            set
            {
                this.ProjectDetail = (global::LightSwitchApplication.Implementation.ProjectDetail)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ProjectDetail");
                }
            }
        }
        
        partial void OnMonthIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Months");
            }
        }
        
        partial void OnEmpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ProjectDetail");
            }
        }
        
        partial void OnProjectIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ProjectDetail");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class GetDateParameter :
        global::LightSwitchApplication.GetDateParameter.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class HoursPerDay :
        global::LightSwitchApplication.HoursPerDay.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Months :
        global::LightSwitchApplication.Months.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Months.DetailsClass.IImplementation.EmployeeMonths
        {
            get
            {
                return this.EmployeeMonths;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Months.DetailsClass.IImplementation.EmployeeProjects
        {
            get
            {
                return this.EmployeeProjects;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PMTeamProject :
        global::LightSwitchApplication.PMTeamProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectDetail :
        global::LightSwitchApplication.ProjectDetail.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProjectDetail.DetailsClass.IImplementation.EmployeeProjects
        {
            get
            {
                return this.EmployeeProjects;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectDetail.DetailsClass.IImplementation.ProjectsInCompany
        {
            get
            {
                return this.ProjectsInCompany;
            }
            set
            {
                this.ProjectsInCompany = (global::LightSwitchApplication.Implementation.ProjectsInCompany)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ProjectsInCompany");
                }
            }
        }
        
        partial void OnAssignProjectIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ProjectsInCompany");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectManagerViewTeamHour :
        global::LightSwitchApplication.ProjectManagerViewTeamHour.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectReport :
        global::LightSwitchApplication.ProjectReport.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectsInCompany :
        global::LightSwitchApplication.ProjectsInCompany.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProjectsInCompany.DetailsClass.IImplementation.AssignProject
        {
            get
            {
                return this.AssignProject;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProjectsInCompany.DetailsClass.IImplementation.ProjectDetails
        {
            get
            {
                return this.ProjectDetails;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectsInDay :
        global::LightSwitchApplication.ProjectsInDay.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TeamProject :
        global::LightSwitchApplication.TeamProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TeamProjectsList :
        global::LightSwitchApplication.TeamProjectsList.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalHour :
        global::LightSwitchApplication.TotalHour.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalHoursAllMonthsForProject :
        global::LightSwitchApplication.TotalHoursAllMonthsForProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalHoursandProjectShare :
        global::LightSwitchApplication.TotalHoursandProjectShare.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalHoursofAllProject :
        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalHoursProjectwiseforMonth :
        global::LightSwitchApplication.TotalHoursProjectwiseforMonth.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalHoursTeamMonthwise :
        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TotalProjectScore :
        global::LightSwitchApplication.TotalProjectScore.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class UtilizationCalculation :
        global::LightSwitchApplication.UtilizationCalculation.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class UtilizationTracker :
        global::LightSwitchApplication.UtilizationTracker.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

