

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class TotalHoursTeamMonthwise : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TotalHoursTeamMonthwise entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TotalHoursTeamMonthwise()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TotalHoursTeamMonthwise(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TotalHoursTeamMonthwise> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalHoursTeamMonthwise_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalHoursTeamMonthwise_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EmpName
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.EmpName);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.EmpName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProjectID
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.ProjectID);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.ProjectID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectName
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.ProjectName);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.ProjectName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Expr1
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.Expr1);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.Expr1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Expr1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Expr1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Expr1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MonthID
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.MonthID);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.MonthID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MonthName
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.MonthName);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.MonthName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthName_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TotalHoursTeamMonthwise,
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass,
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.IImplementation,
                global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.EmpName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass>.Entry
                __TotalHoursTeamMonthwiseEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass>.Entry(
                    global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.__TotalHoursTeamMonthwise_CreateNew,
                    global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.__TotalHoursTeamMonthwise_Created,
                    global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.__TotalHoursTeamMonthwise_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TotalHoursTeamMonthwise __TotalHoursTeamMonthwise_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TotalHoursTeamMonthwise> es)
            {
                return new global::LightSwitchApplication.TotalHoursTeamMonthwise(es);
            }
            private static void __TotalHoursTeamMonthwise_Created(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
            {
                e.TotalHoursTeamMonthwise_Created();
            }
            private static bool __TotalHoursTeamMonthwise_AllowSaveWithErrors(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
            {
                bool result = false;
                e.TotalHoursTeamMonthwise_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string> EmpName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.EmpName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int> ProjectID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.ProjectID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string> ProjectName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.ProjectName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::System.Nullable<decimal>> Expr1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.Expr1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int> MonthID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.MonthID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string> MonthName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties.MonthName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string EmpName { get; set; }
                new int ProjectID { get; set; }
                new string ProjectName { get; set; }
                new global::System.Nullable<decimal> Expr1 { get; set; }
                new int MonthID { get; set; }
                new string MonthName { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Entry
                    EmpName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Entry(
                        "EmpName",
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._EmpName_Stub,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._EmpName_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._EmpName_Validate,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._EmpName_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._EmpName_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._EmpName_OnValueChanged);
                private static void _EmpName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Data> c, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, object sf)
                {
                    c(d, ref d._EmpName, sf);
                }
                private static bool _EmpName_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    bool result = false;
                    e.EmpName_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmpName_Validate(global::LightSwitchApplication.TotalHoursTeamMonthwise e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmpName_Validate(r);
                }
                private static string _EmpName_GetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d)
                {
                    return d.ImplementationEntity.EmpName;
                }
                private static void _EmpName_SetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EmpName = v;
                }
                private static void _EmpName_OnValueChanged(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    e.EmpName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Entry
                    ProjectID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Entry(
                        "ProjectID",
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectID_Stub,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectID_Validate,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectID_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectID_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectID_OnValueChanged);
                private static void _ProjectID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Data> c, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectID, sf);
                }
                private static bool _ProjectID_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    bool result = false;
                    e.ProjectID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectID_Validate(global::LightSwitchApplication.TotalHoursTeamMonthwise e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectID_Validate(r);
                }
                private static int _ProjectID_GetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectID;
                }
                private static void _ProjectID_SetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ProjectID = v;
                }
                private static void _ProjectID_OnValueChanged(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    e.ProjectID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Entry
                    ProjectName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Entry(
                        "ProjectName",
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectName_Stub,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectName_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectName_Validate,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectName_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectName_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._ProjectName_OnValueChanged);
                private static void _ProjectName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Data> c, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectName, sf);
                }
                private static bool _ProjectName_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    bool result = false;
                    e.ProjectName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectName_Validate(global::LightSwitchApplication.TotalHoursTeamMonthwise e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectName_Validate(r);
                }
                private static string _ProjectName_GetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectName;
                }
                private static void _ProjectName_SetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectName = v;
                }
                private static void _ProjectName_OnValueChanged(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    e.ProjectName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Expr1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Expr1",
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._Expr1_Stub,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._Expr1_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._Expr1_Validate,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._Expr1_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._Expr1_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._Expr1_OnValueChanged);
                private static void _Expr1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, object sf)
                {
                    c(d, ref d._Expr1, sf);
                }
                private static bool _Expr1_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    bool result = false;
                    e.Expr1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Expr1_Validate(global::LightSwitchApplication.TotalHoursTeamMonthwise e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Expr1_Validate(r);
                }
                private static global::System.Nullable<decimal> _Expr1_GetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d)
                {
                    return d.ImplementationEntity.Expr1;
                }
                private static void _Expr1_SetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Expr1 = v;
                }
                private static void _Expr1_OnValueChanged(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    e.Expr1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Entry
                    MonthID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Entry(
                        "MonthID",
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthID_Stub,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthID_Validate,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthID_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthID_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthID_OnValueChanged);
                private static void _MonthID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Data> c, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, object sf)
                {
                    c(d, ref d._MonthID, sf);
                }
                private static bool _MonthID_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    bool result = false;
                    e.MonthID_IsReadOnly(ref result);
                    return result;
                }
                private static void _MonthID_Validate(global::LightSwitchApplication.TotalHoursTeamMonthwise e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MonthID_Validate(r);
                }
                private static int _MonthID_GetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d)
                {
                    return d.ImplementationEntity.MonthID;
                }
                private static void _MonthID_SetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, int v)
                {
                    d.ImplementationEntity.MonthID = v;
                }
                private static void _MonthID_OnValueChanged(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    e.MonthID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Entry
                    MonthName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Entry(
                        "MonthName",
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthName_Stub,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthName_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthName_Validate,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthName_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthName_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass.PropertySetProperties._MonthName_OnValueChanged);
                private static void _MonthName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Data> c, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, object sf)
                {
                    c(d, ref d._MonthName, sf);
                }
                private static bool _MonthName_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    bool result = false;
                    e.MonthName_IsReadOnly(ref result);
                    return result;
                }
                private static void _MonthName_Validate(global::LightSwitchApplication.TotalHoursTeamMonthwise e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MonthName_Validate(r);
                }
                private static string _MonthName_GetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d)
                {
                    return d.ImplementationEntity.MonthName;
                }
                private static void _MonthName_SetImplementationValue(global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MonthName = v;
                }
                private static void _MonthName_OnValueChanged(global::LightSwitchApplication.TotalHoursTeamMonthwise e)
                {
                    e.MonthName_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Data _EmpName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Data _ProjectID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Data _ProjectName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, global::System.Nullable<decimal>>.Data _Expr1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, int>.Data _MonthID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursTeamMonthwise, global::LightSwitchApplication.TotalHoursTeamMonthwise.DetailsClass, string>.Data _MonthName;
            
        }
    
        #endregion
    }
    
    #endregion
}
