

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class TotalHoursofAllProject : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TotalHoursofAllProject entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TotalHoursofAllProject()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TotalHoursofAllProject(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TotalHoursofAllProject> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalHoursofAllProject_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalHoursofAllProject_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> TotalofallProjects
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.TotalofallProjects);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.TotalofallProjects, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalofallProjects_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalofallProjects_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalofallProjects_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EmpID
        {
            get
            {
                return global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.EmpID);
            }
            set
            {
                global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.EmpID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TotalHoursofAllProject,
                global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass,
                global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.IImplementation,
                global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.TotalofallProjects;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass>.Entry
                __TotalHoursofAllProjectEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass>.Entry(
                    global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.__TotalHoursofAllProject_CreateNew,
                    global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.__TotalHoursofAllProject_Created,
                    global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.__TotalHoursofAllProject_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TotalHoursofAllProject __TotalHoursofAllProject_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TotalHoursofAllProject> es)
            {
                return new global::LightSwitchApplication.TotalHoursofAllProject(es);
            }
            private static void __TotalHoursofAllProject_Created(global::LightSwitchApplication.TotalHoursofAllProject e)
            {
                e.TotalHoursofAllProject_Created();
            }
            private static bool __TotalHoursofAllProject_AllowSaveWithErrors(global::LightSwitchApplication.TotalHoursofAllProject e)
            {
                bool result = false;
                e.TotalHoursofAllProject_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::System.Nullable<decimal>> TotalofallProjects
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.TotalofallProjects) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, int> EmpID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties.EmpID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Nullable<decimal> TotalofallProjects { get; set; }
                new int EmpID { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::System.Nullable<decimal>>.Entry
                    TotalofallProjects = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "TotalofallProjects",
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._TotalofallProjects_Stub,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._TotalofallProjects_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._TotalofallProjects_Validate,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._TotalofallProjects_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._TotalofallProjects_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._TotalofallProjects_OnValueChanged);
                private static void _TotalofallProjects_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass d, object sf)
                {
                    c(d, ref d._TotalofallProjects, sf);
                }
                private static bool _TotalofallProjects_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursofAllProject e)
                {
                    bool result = false;
                    e.TotalofallProjects_IsReadOnly(ref result);
                    return result;
                }
                private static void _TotalofallProjects_Validate(global::LightSwitchApplication.TotalHoursofAllProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TotalofallProjects_Validate(r);
                }
                private static global::System.Nullable<decimal> _TotalofallProjects_GetImplementationValue(global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass d)
                {
                    return d.ImplementationEntity.TotalofallProjects;
                }
                private static void _TotalofallProjects_SetImplementationValue(global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.TotalofallProjects = v;
                }
                private static void _TotalofallProjects_OnValueChanged(global::LightSwitchApplication.TotalHoursofAllProject e)
                {
                    e.TotalofallProjects_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, int>.Entry
                    EmpID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, int>.Entry(
                        "EmpID",
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._EmpID_Stub,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._EmpID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._EmpID_Validate,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._EmpID_GetImplementationValue,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._EmpID_SetImplementationValue,
                        global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass.PropertySetProperties._EmpID_OnValueChanged);
                private static void _EmpID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass d, object sf)
                {
                    c(d, ref d._EmpID, sf);
                }
                private static bool _EmpID_ComputeIsReadOnly(global::LightSwitchApplication.TotalHoursofAllProject e)
                {
                    bool result = false;
                    e.EmpID_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmpID_Validate(global::LightSwitchApplication.TotalHoursofAllProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmpID_Validate(r);
                }
                private static int _EmpID_GetImplementationValue(global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass d)
                {
                    return d.ImplementationEntity.EmpID;
                }
                private static void _EmpID_SetImplementationValue(global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass d, int v)
                {
                    d.ImplementationEntity.EmpID = v;
                }
                private static void _EmpID_OnValueChanged(global::LightSwitchApplication.TotalHoursofAllProject e)
                {
                    e.EmpID_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, global::System.Nullable<decimal>>.Data _TotalofallProjects;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TotalHoursofAllProject, global::LightSwitchApplication.TotalHoursofAllProject.DetailsClass, int>.Data _EmpID;
            
        }
    
        #endregion
    }
    
    #endregion
}
