

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class ProjectsInDay : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProjectsInDay entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProjectsInDay()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProjectsInDay(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProjectsInDay> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProjectsInDay.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsInDay_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsInDay_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime c_Date
        {
            get
            {
                return global::LightSwitchApplication.ProjectsInDay.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.c_Date);
            }
            set
            {
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.c_Date, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Hours
        {
            get
            {
                return global::LightSwitchApplication.ProjectsInDay.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.Hours);
            }
            set
            {
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.Hours, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hours_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hours_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hours_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SubProject
        {
            get
            {
                return global::LightSwitchApplication.ProjectsInDay.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.SubProject);
            }
            set
            {
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.SubProject, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubProject_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubProject_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubProject_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectName
        {
            get
            {
                return global::LightSwitchApplication.ProjectsInDay.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.ProjectName);
            }
            set
            {
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.ProjectName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EmpID
        {
            get
            {
                return global::LightSwitchApplication.ProjectsInDay.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.EmpID);
            }
            set
            {
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.EmpID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProjectsInDay,
                global::LightSwitchApplication.ProjectsInDay.DetailsClass,
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.c_Date;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass>.Entry
                __ProjectsInDayEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProjectsInDay.DetailsClass.__ProjectsInDay_CreateNew,
                    global::LightSwitchApplication.ProjectsInDay.DetailsClass.__ProjectsInDay_Created,
                    global::LightSwitchApplication.ProjectsInDay.DetailsClass.__ProjectsInDay_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProjectsInDay __ProjectsInDay_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProjectsInDay> es)
            {
                return new global::LightSwitchApplication.ProjectsInDay(es);
            }
            private static void __ProjectsInDay_Created(global::LightSwitchApplication.ProjectsInDay e)
            {
                e.ProjectsInDay_Created();
            }
            private static bool __ProjectsInDay_AllowSaveWithErrors(global::LightSwitchApplication.ProjectsInDay e)
            {
                bool result = false;
                e.ProjectsInDay_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::System.DateTime> c_Date
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.c_Date) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, decimal> Hours
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.Hours) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string> SubProject
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.SubProject) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string> ProjectName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.ProjectName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, int> EmpID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties.EmpID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.DateTime c_Date { get; set; }
                new decimal Hours { get; set; }
                new string SubProject { get; set; }
                new string ProjectName { get; set; }
                new int EmpID { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::System.DateTime>.Entry
                    c_Date = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::System.DateTime>.Entry(
                        "c_Date",
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._c_Date_Stub,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._c_Date_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._c_Date_Validate,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._c_Date_GetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._c_Date_SetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._c_Date_OnValueChanged);
                private static void _c_Date_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ProjectsInDay.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Date, sf);
                }
                private static bool _c_Date_ComputeIsReadOnly(global::LightSwitchApplication.ProjectsInDay e)
                {
                    bool result = false;
                    e.c_Date_IsReadOnly(ref result);
                    return result;
                }
                private static void _c_Date_Validate(global::LightSwitchApplication.ProjectsInDay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.c_Date_Validate(r);
                }
                private static global::System.DateTime _c_Date_GetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d)
                {
                    return d.ImplementationEntity.c_Date;
                }
                private static void _c_Date_SetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.c_Date = global::LightSwitchApplication.ProjectsInDay.DetailsClass.TruncateDate(v);
                }
                private static void _c_Date_OnValueChanged(global::LightSwitchApplication.ProjectsInDay e)
                {
                    e.c_Date_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, decimal>.Entry
                    Hours = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, decimal>.Entry(
                        "Hours",
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._Hours_Stub,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._Hours_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._Hours_Validate,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._Hours_GetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._Hours_SetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._Hours_OnValueChanged);
                private static void _Hours_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ProjectsInDay.DetailsClass d, object sf)
                {
                    c(d, ref d._Hours, sf);
                }
                private static bool _Hours_ComputeIsReadOnly(global::LightSwitchApplication.ProjectsInDay e)
                {
                    bool result = false;
                    e.Hours_IsReadOnly(ref result);
                    return result;
                }
                private static void _Hours_Validate(global::LightSwitchApplication.ProjectsInDay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Hours_Validate(r);
                }
                private static decimal _Hours_GetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d)
                {
                    return d.ImplementationEntity.Hours;
                }
                private static void _Hours_SetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Hours = v;
                }
                private static void _Hours_OnValueChanged(global::LightSwitchApplication.ProjectsInDay e)
                {
                    e.Hours_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Entry
                    SubProject = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Entry(
                        "SubProject",
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._SubProject_Stub,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._SubProject_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._SubProject_Validate,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._SubProject_GetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._SubProject_SetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._SubProject_OnValueChanged);
                private static void _SubProject_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectsInDay.DetailsClass d, object sf)
                {
                    c(d, ref d._SubProject, sf);
                }
                private static bool _SubProject_ComputeIsReadOnly(global::LightSwitchApplication.ProjectsInDay e)
                {
                    bool result = false;
                    e.SubProject_IsReadOnly(ref result);
                    return result;
                }
                private static void _SubProject_Validate(global::LightSwitchApplication.ProjectsInDay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SubProject_Validate(r);
                }
                private static string _SubProject_GetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d)
                {
                    return d.ImplementationEntity.SubProject;
                }
                private static void _SubProject_SetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SubProject = v;
                }
                private static void _SubProject_OnValueChanged(global::LightSwitchApplication.ProjectsInDay e)
                {
                    e.SubProject_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Entry
                    ProjectName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Entry(
                        "ProjectName",
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._ProjectName_Stub,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._ProjectName_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._ProjectName_Validate,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._ProjectName_GetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._ProjectName_SetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._ProjectName_OnValueChanged);
                private static void _ProjectName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectsInDay.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectName, sf);
                }
                private static bool _ProjectName_ComputeIsReadOnly(global::LightSwitchApplication.ProjectsInDay e)
                {
                    bool result = false;
                    e.ProjectName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectName_Validate(global::LightSwitchApplication.ProjectsInDay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectName_Validate(r);
                }
                private static string _ProjectName_GetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectName;
                }
                private static void _ProjectName_SetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectName = v;
                }
                private static void _ProjectName_OnValueChanged(global::LightSwitchApplication.ProjectsInDay e)
                {
                    e.ProjectName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, int>.Entry
                    EmpID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, int>.Entry(
                        "EmpID",
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._EmpID_Stub,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._EmpID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._EmpID_Validate,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._EmpID_GetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._EmpID_SetImplementationValue,
                        global::LightSwitchApplication.ProjectsInDay.DetailsClass.PropertySetProperties._EmpID_OnValueChanged);
                private static void _EmpID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProjectsInDay.DetailsClass d, object sf)
                {
                    c(d, ref d._EmpID, sf);
                }
                private static bool _EmpID_ComputeIsReadOnly(global::LightSwitchApplication.ProjectsInDay e)
                {
                    bool result = false;
                    e.EmpID_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmpID_Validate(global::LightSwitchApplication.ProjectsInDay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmpID_Validate(r);
                }
                private static int _EmpID_GetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d)
                {
                    return d.ImplementationEntity.EmpID;
                }
                private static void _EmpID_SetImplementationValue(global::LightSwitchApplication.ProjectsInDay.DetailsClass d, int v)
                {
                    d.ImplementationEntity.EmpID = v;
                }
                private static void _EmpID_OnValueChanged(global::LightSwitchApplication.ProjectsInDay e)
                {
                    e.EmpID_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, global::System.DateTime>.Data _c_Date;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, decimal>.Data _Hours;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Data _SubProject;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, string>.Data _ProjectName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectsInDay, global::LightSwitchApplication.ProjectsInDay.DetailsClass, int>.Data _EmpID;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class TeamProject : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TeamProject entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TeamProject()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TeamProject(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TeamProject> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TeamProject.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamProject_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeamProject_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> ManagerID
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ManagerID);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ManagerID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ManagerID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ManagerID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ManagerID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> EmpID
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.EmpID);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.EmpID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string emprole1
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.emprole1);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.emprole1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void emprole1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void emprole1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void emprole1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string emprole2
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.emprole2);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.emprole2, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void emprole2_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void emprole2_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void emprole2_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ID);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> ProjectID
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ProjectID);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ProjectID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Expr1
        {
            get
            {
                return global::LightSwitchApplication.TeamProject.DetailsClass.GetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.Expr1);
            }
            set
            {
                global::LightSwitchApplication.TeamProject.DetailsClass.SetValue(this, global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.Expr1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Expr1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Expr1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Expr1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TeamProject,
                global::LightSwitchApplication.TeamProject.DetailsClass,
                global::LightSwitchApplication.TeamProject.DetailsClass.IImplementation,
                global::LightSwitchApplication.TeamProject.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ManagerID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass>.Entry
                __TeamProjectEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass>.Entry(
                    global::LightSwitchApplication.TeamProject.DetailsClass.__TeamProject_CreateNew,
                    global::LightSwitchApplication.TeamProject.DetailsClass.__TeamProject_Created,
                    global::LightSwitchApplication.TeamProject.DetailsClass.__TeamProject_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TeamProject __TeamProject_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TeamProject> es)
            {
                return new global::LightSwitchApplication.TeamProject(es);
            }
            private static void __TeamProject_Created(global::LightSwitchApplication.TeamProject e)
            {
                e.TeamProject_Created();
            }
            private static bool __TeamProject_AllowSaveWithErrors(global::LightSwitchApplication.TeamProject e)
            {
                bool result = false;
                e.TeamProject_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TeamProject.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>> ManagerID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ManagerID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>> EmpID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.EmpID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string> emprole1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.emprole1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string> emprole2
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.emprole2) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>> ProjectID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.ProjectID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int> Expr1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties.Expr1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Nullable<int> ManagerID { get; set; }
                new global::System.Nullable<int> EmpID { get; set; }
                new string emprole1 { get; set; }
                new string emprole2 { get; set; }
                new int ID { get; set; }
                new global::System.Nullable<int> ProjectID { get; set; }
                new int Expr1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Entry
                    ManagerID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Entry(
                        "ManagerID",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ManagerID_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ManagerID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ManagerID_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ManagerID_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ManagerID_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ManagerID_OnValueChanged);
                private static void _ManagerID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._ManagerID, sf);
                }
                private static bool _ManagerID_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.ManagerID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ManagerID_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ManagerID_Validate(r);
                }
                private static global::System.Nullable<int> _ManagerID_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.ManagerID;
                }
                private static void _ManagerID_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.ManagerID = v;
                }
                private static void _ManagerID_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.ManagerID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Entry
                    EmpID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Entry(
                        "EmpID",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._EmpID_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._EmpID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._EmpID_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._EmpID_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._EmpID_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._EmpID_OnValueChanged);
                private static void _EmpID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._EmpID, sf);
                }
                private static bool _EmpID_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.EmpID_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmpID_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmpID_Validate(r);
                }
                private static global::System.Nullable<int> _EmpID_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.EmpID;
                }
                private static void _EmpID_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.EmpID = v;
                }
                private static void _EmpID_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.EmpID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Entry
                    emprole1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Entry(
                        "emprole1",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole1_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole1_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole1_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole1_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole1_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole1_OnValueChanged);
                private static void _emprole1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._emprole1, sf);
                }
                private static bool _emprole1_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.emprole1_IsReadOnly(ref result);
                    return result;
                }
                private static void _emprole1_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.emprole1_Validate(r);
                }
                private static string _emprole1_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.emprole1;
                }
                private static void _emprole1_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, string v)
                {
                    d.ImplementationEntity.emprole1 = v;
                }
                private static void _emprole1_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.emprole1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Entry
                    emprole2 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Entry(
                        "emprole2",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole2_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole2_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole2_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole2_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole2_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._emprole2_OnValueChanged);
                private static void _emprole2_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._emprole2, sf);
                }
                private static bool _emprole2_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.emprole2_IsReadOnly(ref result);
                    return result;
                }
                private static void _emprole2_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.emprole2_Validate(r);
                }
                private static string _emprole2_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.emprole2;
                }
                private static void _emprole2_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, string v)
                {
                    d.ImplementationEntity.emprole2 = v;
                }
                private static void _emprole2_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.emprole2_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ID_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ID = v;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Entry
                    ProjectID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Entry(
                        "ProjectID",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ProjectID_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ProjectID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ProjectID_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ProjectID_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ProjectID_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._ProjectID_OnValueChanged);
                private static void _ProjectID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectID, sf);
                }
                private static bool _ProjectID_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.ProjectID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectID_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectID_Validate(r);
                }
                private static global::System.Nullable<int> _ProjectID_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectID;
                }
                private static void _ProjectID_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.ProjectID = v;
                }
                private static void _ProjectID_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.ProjectID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Entry
                    Expr1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Entry(
                        "Expr1",
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._Expr1_Stub,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._Expr1_ComputeIsReadOnly,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._Expr1_Validate,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._Expr1_GetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._Expr1_SetImplementationValue,
                        global::LightSwitchApplication.TeamProject.DetailsClass.PropertySetProperties._Expr1_OnValueChanged);
                private static void _Expr1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TeamProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.TeamProject.DetailsClass d, object sf)
                {
                    c(d, ref d._Expr1, sf);
                }
                private static bool _Expr1_ComputeIsReadOnly(global::LightSwitchApplication.TeamProject e)
                {
                    bool result = false;
                    e.Expr1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Expr1_Validate(global::LightSwitchApplication.TeamProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Expr1_Validate(r);
                }
                private static int _Expr1_GetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d)
                {
                    return d.ImplementationEntity.Expr1;
                }
                private static void _Expr1_SetImplementationValue(global::LightSwitchApplication.TeamProject.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Expr1 = v;
                }
                private static void _Expr1_OnValueChanged(global::LightSwitchApplication.TeamProject e)
                {
                    e.Expr1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Data _ManagerID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Data _EmpID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Data _emprole1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, string>.Data _emprole2;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, global::System.Nullable<int>>.Data _ProjectID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TeamProject, global::LightSwitchApplication.TeamProject.DetailsClass, int>.Data _Expr1;
            
        }
    
        #endregion
    }
    
    #endregion
}
